//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Files struct {
	ID           uuid.UUID `sql:"primary_key"`
	Sha256       string
	OriginalName string
	MimeType     string
	FileSize     int64
	UploadIP     string
	UserAgent    *string
	Secret       *string
	MgmtToken    string
	ExpiresAt    time.Time
	Removed      *bool
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
}
