//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Urls = newUrlsTable("public", "urls", "")

type urlsTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	OriginalURL postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UrlsTable struct {
	urlsTable

	EXCLUDED urlsTable
}

// AS creates new UrlsTable with assigned alias
func (a UrlsTable) AS(alias string) *UrlsTable {
	return newUrlsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UrlsTable with assigned schema name
func (a UrlsTable) FromSchema(schemaName string) *UrlsTable {
	return newUrlsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UrlsTable with assigned table prefix
func (a UrlsTable) WithPrefix(prefix string) *UrlsTable {
	return newUrlsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UrlsTable with assigned table suffix
func (a UrlsTable) WithSuffix(suffix string) *UrlsTable {
	return newUrlsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUrlsTable(schemaName, tableName, alias string) *UrlsTable {
	return &UrlsTable{
		urlsTable: newUrlsTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newUrlsTableImpl("", "excluded", ""),
	}
}

func newUrlsTableImpl(schemaName, tableName, alias string) urlsTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		OriginalURLColumn = postgres.StringColumn("original_url")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		allColumns        = postgres.ColumnList{IDColumn, OriginalURLColumn, CreatedAtColumn}
		mutableColumns    = postgres.ColumnList{OriginalURLColumn, CreatedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return urlsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		OriginalURL: OriginalURLColumn,
		CreatedAt:   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
